//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWinkellijst_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        public int BestellingID { get; set; }
        public string Artikel { get; set; }
        public Nullable<decimal> Prijs { get; set; }
        public int KlantID { get; set; }
    
        public virtual Klant Klant { get; set; }
    }
}
