//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWinkellijst_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LijstItem
    {
        public int LijstItemId { get; set; }
        public Nullable<int> WinkellijstId { get; set; }
        public int Aantal { get; set; }
    
        public virtual Winkellijst Winkellijst { get; set; }
    }
}
