//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWinkellijst_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PR_r0739290Entities : DbContext
    {
        public PR_r0739290Entities()
            : base("name=PR_r0739290Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gebruiker> Gebruiker { get; set; }
        public virtual DbSet<LijstItem> LijstItem { get; set; }
        public virtual DbSet<Locatie> Locatie { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Winkellijst> Winkellijst { get; set; }
    }
}
