//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWinkellijst_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public Nullable<int> LocatieId { get; set; }
        public string Naam { get; set; }
        public Nullable<decimal> Prijs { get; set; }
        public Nullable<int> Hoeveelheid { get; set; }
    
        public virtual Locatie Locatie { get; set; }
    }
}
