//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWinkellijst_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider
    {
        public int RiderId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int CountryID { get; set; }
        public int TeamID { get; set; }
        public string Bike { get; set; }
        public int Number { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Team Team { get; set; }
    }
}
