//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileWinkellijst_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int CountryID { get; set; }
        public int RaceID { get; set; }
        public int Number { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool Paid { get; set; }
        public string Address { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Race Race { get; set; }
    }
}
